version: "3.7"

services:
  react:
    build:
      context: ./
      dockerfile: Dockerfile-react
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - dev_network
      - infra

networks:
  dev_network:
  infra:
