version: "3.7"

services:
  application:
    container_name: spring-boot-1
    build:
      context: ./
      dockerfile: Dockerfile-prod
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db_dev:3306/zirraforming?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ssafy
      SPRING_DATASOURCE_PASSWORD: ssafywlfkvhald
      SPRING_REDIS_HOST: redis_dev
      SPRING_REDIS_PORT: 6379
      ENV_IDLE_PROFILE: production-set1
    volumes:
      - /home/ubuntu/front/build/images:/images
    networks:
      - infra
      - dev_network

networks:
  infra:
  dev_network:
